name: release-toolbelt

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v1
      - uses: docker/setup-qemu-action@v1

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v3
        id: docker_meta
        with:
          images: ghcr.io/suborbital/toolbelt
          # tag image `sha-abc1234` if git reference is not a tag
          # tag image with semver if tag is prefixed with `scn-`
          tags: |
            type=sha,enable=true
          flavor: |
            latest=auto
      - uses: docker/build-push-action@v2
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
